[회원 관리] 사용자 정보 CRUD 기능 구현 및 개선 (#2, #4, #5)
ssg-240304-java2/shop-404NotFound pull request #27
Opened 2024-06-23 14:05 UTC by kebin0591

## 개요
이 풀 리퀘스트는 회원 관리 기능의 기본적인 CRUD 작업을 구현하고 개선하는 내용을 포함하고 있습니다. 주요 변경 사항으로는 사용자 정보 수정 기능 개선, 로깅 강화, 그리고 프론트엔드 상호작용 개선이 있습니다.

## 주요 변경 사항
1. 사용자 관리 기본 구조 구현
   - UserMapper 인터페이스 및 UserDTO 모델 클래스 생성
   - UserDAO 인터페이스 및 UserDAOImpl 클래스 구현
   - UserService 인터페이스 및 UserServiceImpl 클래스 구현
   - UserController 클래스 추가

2. 데이터베이스 연동
   - UserMapper.xml에 CRUD 관련 SQL 쿼리 구현
   - application.yml에 데이터베이스 설정 추가

3. 사용자 CRUD 기능 구현
   - 사용자 조회, 추가, 수정, 삭제 기능 개발
   - 사용자 로그인 기능 구현

4. 프론트엔드 개발
   - 사용자 목록, 수정, 로그인, 등록 페이지 템플릿 추가
   - 메인 페이지(index.html) 임시 수정

5. 코드 품질 개선
   - JavaDoc 및 설명 주석 추가로 문서화 강화
   - null 체크 로직 개선 및 예외 처리 강화
   - ResultMap 도입으로 ORM 매핑 개선

6. 로깅 시스템 구축
   - UserController, UserServiceImpl에 상세 로깅 추가
   - application.yml에서 로깅 레벨 조정

7. 보안 및 데이터 무결성 강화
   - 사용자 랭크 수정 방지 로직 추가
   - 신규 사용자 등록 시 기본 랭크 설정

8. 성능 및 사용자 경험 개선
   - 프론트엔드에서 사용자 수정 링크 클릭 시 AJAX 처리 추가
   - 사용자 목록 및 수정 페이지 UI/UX 개선

9. 테스트 및 디버깅
   - UserMapperTest 작성 (추가 개선 예정)
   - 각 기능에 대한 테스트 및 버그 수정 수행
## 테스트 및 디버깅
모든 기능에 대한 테스트를 수행, 발견된 모든 버그를 성공적으로 수정 -완-

- 테스트 완료: 사용자 정보 조회, 수정, 삭제 기능
- 디버깅 완료: 랭크 수정 방지, 로깅 오류, AJAX 요청 처리

## 관련 이슈
- #2
- #4
- #5

## 리뷰 요청사항
- 코드의 전반적인 구조와 가독성
- 예외 처리의 적절성
- 로깅 레벨 및 내용의 적절성
- 프론트엔드와 백엔드의 연동 부분

리뷰 부탁드려용용~~

## 추가 노트
이 PR은 현재 진행 중인 회원 관리 기능 구현 스프린트의 일부입니다. 각 메서드에 세부적인 비즈니스 로직 추가 예정이고, 프론트를 개발하면서 필요한 기능이 있으면 추가수정 예정입니다. 또 템플릿이 정해져서 프론트 작업을 다시 하게 된다면 그에 맞춰서 또 수정 예정입니당.

2024-06-23 16:37 UTC, kebin0591 commented
리뷰... 부탁....드려요,....

2024-06-24 00:04 UTC, yujin4sth00 approved these changes
확인했습니다.
UI와 회원 정보 수정 되는 건 확인 사진을 봤습니다.

2024-06-24 01:35 UTC, sanghyeonJwa commented
혹시 UserDAO 와 UserMapper의 차이가 뭔가요?

2024-06-24 01:38 UTC, sanghyeonJwa commented on src/main/java/com/nf404/devshop/dao/UserDAO.java
> +}
이 부분과 UserMapper와의 차이가 궁금합니다!

2024-06-24 01:43 UTC, sanghyeonJwa commented on src/main/java/com/nf404/devshop/service/impl/UserServiceImpl.java
> +    }
트랜잭션 어노테이션을 붙여야 하지 않을까 싶습니다..!

2024-06-24 05:22 UTC, kebin0591 commented on src/main/java/com/nf404/devshop/dao/UserDAO.java
> +}
> 이 부분과 UserMapper와의 차이가 궁금합니다!

매퍼는 mybatis용으로 만들었고 쿼리 작성용이거 DAO는 더 높은(?) 추상화를 제공해야해서 저렇게 나눴던거같습니다! 그리고 DAO에 대한 구현은 impl에서 해서 저렇게 짰던 것 같습니다.

2024-06-24 05:23 UTC, kebin0591 commented on src/main/java/com/nf404/devshop/service/impl/UserServiceImpl.java
> +    }
> 트랜잭션 어노테이션을 붙여야 하지 않을까 싶습니다..!

오 이따 자세히 알려주시죠

2024-06-24 05:27 UTC, DokaDev requested changes

2024-06-24 05:27 UTC, DokaDev commented on src/main/java/com/nf404/devshop/controller/UserController.java
> +    @GetMapping("/delete/{userId}")
이건 Post요청으로 처리하시는게 어떨까 하는 의견입니다.

2024-06-24 05:27 UTC, DokaDev commented on src/main/java/com/nf404/devshop/controller/UserController.java
> +    @GetMapping("/delete/{userId}")
url만으로도 path로 지정된 번호에 해당하는 사용자 정보를 지울 수 있게 되는 문제가 생길 수 있지 않을까 싶네요.

2024-06-24 05:27 UTC, DokaDev commented on src/main/resources/application.yml
url/username/password는 이전 값으로 바꿔주세요. 실 인증정보가 노출되지 않는 것이 바람직해 보입니다.

2024-06-24 05:35 UTC, kebin0591 commented on src/main/resources/application.yml
> url/username/password는 이전 값으로 바꿔주세요. 실 인증정보가 노출되지 않는 것이 바람직해 보입니다.

조금더 자세히 설명해주실수 있나용?

2024-06-24 05:36 UTC, kebin0591 commented on src/main/java/com/nf404/devshop/controller/UserController.java
> +    @GetMapping("/delete/{userId}")
> url만으로도 path로 지정된 번호에 해당하는 사용자 정보를 지울 수 있게 되는 문제가 생길 수 있지 않을까 싶네요.

생각해보니 그런것 같습니다. 보완하겠습니다~

2024-06-24 06:38 UTC, sanghyeonJwa commented
구현하신 부분 도메인 (member 혹은 user) 패키지 안에 넣어주시면 감사하겠습니다!

2024-06-24 06:48 UTC, DokaDev commented
아키텍처 간 의존성 주입 형태가 다소 부적절하게 사용된 부분이 보입니다. Service 및 Dao/Mapper단의 의존성주입 관계 확인 후 조정부탁드립니다. Dao/Mapper을 둘로 나눌 필요가 굳이 없다면 한 개념(sugg. 매퍼로...)으로 통일해주시면 좋겠습니다.

2024-06-24 07:24 UTC, zZerorok commented
꼼꼼하게 작성하셨네요. 
보고 참고할게요~~

2024-06-24 07:37 UTC, kebin0591 commented
> 꼼꼼하게 작성하셨네요. 
> 보고 참고할게요~~

어어.... 퍼가실때 출처 필수입니다~

2024-06-25 00:02 UTC, kebin0591 commented on src/main/java/com/nf404/devshop/service/impl/UserServiceImpl.java
> +    }
@sanghyeonJwa 서비스 부분에 CUD 관련하여 트랙잭션 어노테이션으로 수정 완료하였습니다! 
R부분은 @Transactional(readOnly = true)를 이용하여 읽기 전용으로만 했습니다~!

2024-06-25 00:27 UTC, kebin0591 commented on src/main/java/com/nf404/devshop/controller/UserController.java
> +    @GetMapping("/delete/{userId}")
> url만으로도 path로 지정된 번호에 해당하는 사용자 정보를 지울 수 있게 되는 문제가 생길 수 있지 않을까 싶네요.

수정 완료해서 get에서 post로 바꿨습니다~

2024-06-25 01:08 UTC, merged