Feat/product crud base: service & dao layer, mapper 구현
ssg-240304-java2/shop-404NotFound pull request #30
Opened 2024-06-24 01:09 UTC by sanghyeonJwa

2024-06-24 05:41 UTC, kebin0591 approved these changes

2024-06-24 05:41 UTC, kebin0591 commented on src/main/java/com/nf404/devshop/product/service/ProductService.java
서비스 단에서 예외처리 같은 것도 나중에 추가하면 좋을 것 같습니다! 고생하셨습니다!

2024-06-24 05:43 UTC, sanghyeonJwa commented on src/main/java/com/nf404/devshop/product/service/ProductService.java
넵 알겠습니다!

2024-06-24 06:31 UTC, DokaDev requested changes

2024-06-24 06:31 UTC, DokaDev commented on src/main/resources/mappers/product/CategoryMapper.xml
> +    <select id="getByRefCategoryCode" resultMap="categoryResultMap">
id명만으로는 dao 메소드의 동작을 유추하기가 다소 어렵습니다. 이름 조정부탁드립니다.

2024-06-24 06:31 UTC, DokaDev commented on src/main/resources/mappers/product/CategoryMapper.xml
> +    <select id="getByRefCategoryCode" resultMap="categoryResultMap">
selectSubCategoriesByParentCategoryCode()

2024-06-24 06:31 UTC, DokaDev commented on src/main/resources/mappers/product/CategoryMapper.xml
> +    <insert id="insertCategory">
parameterType="com.....xxxDto"

xxx.ref_category_code;

2024-06-25 01:02 UTC, sanghyeonJwa commented on src/main/resources/mappers/product/CategoryMapper.xml
> +    <select id="getByRefCategoryCode" resultMap="categoryResultMap">
좀더 직관적인 이름으로 수정했습니다!

2024-06-25 01:05 UTC, sanghyeonJwa commented on src/main/resources/mappers/product/CategoryMapper.xml
> +    <insert id="insertCategory">
현재 이 부분은 참조하는 parameter가 1개일 경우 자동으로 mapping 되는 것으로 알고 있어서 추후에 문제가 생기거나 코드 로직을 이해하는데 어렵다면 추가하겠습니다!

2024-06-25 02:24 UTC, kebin0591 approved these changes
수정하신 내용 확인했습니다!

2024-06-25 06:54 UTC, DokaDev approved these changes

2024-06-25 06:55 UTC, merged